# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Friend.Media Performance e Conteúdo
title2: Construa conexões de dependência e eduque sua base
email: friend@friend.media
description: >- # this means to ignore newlines until "baseurl:"
  A F.M é uma ação específica de auxílio aos lojistas virtuais que pretendem
  melhorar seu ecommerce performando resultados através de bons e ricos conteúdos e o impulsionamento de mídias,
  tornando, assim, o site de lojas virtuais um celeiro de atração de conteúdo e entretenimento que causam a 
  dependência do usuários, para que, estes, não só atinjam o obetivo da compra, mas que tenha uma boa experiência. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://friend.media" # the base hostname & protocol for your site, e.g. http://friend.media
twitter_username: friend__media

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
