# Welcome to Jekyll!

title: Friend.Media Performance e Conteúdo
title2: Construa conexões de dependência e eduque sua base
email: friend@friend.media
description: >- # this means to ignore newlines until "baseurl:"
  A F.M é uma ação específica de auxílio aos lojistas virtuais que pretendem
  melhorar seu ecommerce performando resultados através de bons e ricos conteúdos e o impulsionamento de mídias,
  tornando, assim, o site de lojas virtuais um celeiro de atração de conteúdo e entretenimento que causam a 
  dependência do usuários, para que, estes, não só atinjam o obetivo da compra, mas que tenha uma boa experiência. 
baseurl: "/friend.media"
url: "http://friend.media"
twitter_username: friend__media

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed
